@startuml
actor User
participant "GameLogic" as GameLogic
participant "Map" as Map
participant "Room" as Room
participant "Tile" as Tile

User -> GameLogic: startGame()
GameLogic -> Map: loadMap()
loop for number of rooms
    Map -> Room: loadRoom()
    loop for number of tiles
        Room -> Tile: loadTile()
    end
end
GameLogic --> Map: distributeItems
GameLogic --> Map: distributeActors
@enduml